### ISSUE TITLE
OTG+MV - Creating 2 worlds with same custom biomes causes error on creation

### ISSUE THREAD

**Issue by PikachuEXE** [PG85/OpenTerrainGenerator#132]
If there is any more info you need please let me know

#### Env
Spigot for 1.12.2 build 1520
Multiverse-Core-2.5.0
Biome Bundle: https://minecraft.curseforge.com/projects/biome-bundle
No other world modification mod/plugins installed

#### Steps
- Extract preset folder into folder with new world name
- `mv create world_name normal -g OpenTerrainGenerator`
- Repeat for 2nd world
- Error reported in game and server log

#### Log
```
Caused by: java.lang.AssertionError: Biome ID #165 returns custom biome #417 instead of its own.
  at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
  at com.pg85.otg.bukkit.OTGBiomeBase.createInstance(OTGBiomeBase.java:141) ~[?:?]
  at com.pg85.otg.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43) ~[?:?]
  at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:171) ~[?:?]
  at com.pg85.otg.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:1646) ~[?:?]
  at com.pg85.otg.configuration.ServerConfigProvider.indexSettings(ServerConfigProvider.java:264) ~[?:?]
  at com.pg85.otg.configuration.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:135) ~[?:?]
  at com.pg85.otg.configuration.ServerConfigProvider.loadSettings(ServerConfigProvider.java:79) ~[?:?]
  at com.pg85.otg.configuration.ServerConfigProvider.<init>(ServerConfigProvider.java:68) ~[?:?]
  at com.pg85.otg.bukkit.OTGPlugin.getDefaultWorldGenerator(OTGPlugin.java:137) ~[?:?]
  at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311) ~[spigot.jar:git-Spigot-4bd94dc-aa34e9b]
  at org.bukkit.WorldCreator.generator(WorldCreator.java:183) ~[spigot.jar:git-Spigot-4bd94dc-aa34e9b]
  at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240) ~[?:?]
  at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) ~[?:?]
  at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
  at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
  at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
  at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) ~[?:?]
  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-4bd94dc-aa34e9b]
  ... 15 more
```

**Comment by smellyonionman** [comment]
Well, isn't that weird... I just opened a ticket regarding generation errors with Biome 165, aka Mesa (Bryce) - maybe these are related.  Did you get similar Assertion Errors naming different biome IDs than 165?

**Comment by PikachuEXE** [comment]
I even removed the custom biome 417 from the config for 2nd world but that doesn't work...
Maybe I can try to remove 165?

**Comment by PikachuEXE** [comment]
Wait, even I removed it 165 is built-in biome, it can't be removed...

**Comment by smellyonionman** [comment]
...since I've been having problems with Mesa (Bryce), you can try what I did - I took 416 and 417 out of the WorldConfig file (both are Bryce variants.)  I opened up Mesa (Bryce).bc (that's 165) and added line 
"ReplaceBiomeToName: Mesa" below the BiomeColor.  Then I changed line 112 "SurfaceAndGroundControl" from "MesaBryce" to "Mesa."  You may also want to raise the BiomeHeight slightly.

This has effectively swapped Mesa Bryce for Mesa without changing my seed so I can regenerate the chunks when a fix is released.  Or do something more drastic if that turns out to be a bad plan, lol.

**Comment by PG85** [comment]
Hey, thanks for reporting this. Will take a look at OTG+MV for the next release.

**Comment by norusk** [comment]
Running into the same problem with Spigot 1.12.2, Multiverse Core Build 719, OTG 1.12.2 v6, BiomesBundle Version 6.1 for Bukkit 1.12.2 as described by PikachuEXE.

```
Caused by: java.lang.AssertionError: Biome ID #165 returns custom biome #417 instead of its own.
  at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
```

Changing the WorldConfig an the Mesa (Bryce).bc as described by adamlaughlin didnt solve the problem. After deleting the world folder, exception differs:

```
Caused by: java.lang.AssertionError: jBiome ID #165 returns custom biome #417 instead of its own.
  at com.pg85.otg.bukkit.OTGBiomeBase.checkRegistry(OTGBiomeBase.java:153) ~[?:?]
```

In the Biomes Folder there are a [couple of files](https://github.com/BiomeBundle/BiomeBundle/search?utf8=%E2%9C%93&q=SurfaceAndGroundControl%3A+MesaBryce&type=) with that "SurfaceAndGroundControl: MesaBryce". Do I have to change the two lines  Workaround for all the files? 

> ReplaceBiomeToName: Mesa" below the BiomeColor. Then I changed line 112 "SurfaceAndGroundControl" from "MesaBryce" to "Mesa." You may also want to raise the BiomeHeight slightly.

**Comment by FrakTech** [comment]
I'm having this same issue. Just curious if there is any timeline on a fix.

I posted a more in depth description as will in the following:
https://github.com/PG85/OpenTerrainGenerator/issues/132#issuecomment-436008093

**Comment by PG85** [comment]
Biome id conflicts should be fixed with v7, which uses dynamic id's. Not sure about generating 2 dimensions using the same preset, would have to test. We don't currently support that for Forge either though.

**Comment by PG85** [comment]
Please let me know if this works for you with v7/v8 (available on the discord), and feel free to reopen this issue if the problem persists.
